output_dir: ./output/cotta
optimization:
  eta: 1
  steps: 1
  optimizer: sgd
  lr: 0.01
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0
  dampening: 0.0

model:
  method: cotta
  arch: resnet50
  update_bn_only: false