output_dir: ./output/
exp_type: each_shift_reset

dataset:
  name: imagenetc
  paths:
    imagenet: '<path to imagenet>'
    imagenetc: '<path to imagenet-c>'
    imagenetr: '<path to imagenet-r>'
    imagenet3dcc: '<path to imagenet-3d>'
  initial_data_size: 500
  spatial_dim_size: 224
  transforms: true
  r_dataset: false
  shuffle: true
  batch_size: 64
  num_classes: 1000

evaluation:
  test_val: false # add imagenet validation set at the end of test set
  level: 5
  corruption: defocus_blur
  eta: 1 # 0-1
  single_model: false
  
optimization:
  steps: 1
  optimizer: sgd
  lr: 0.00025
  momentum: 0.9

model:
  method: basic
  arch: resnet50
  update_bn_only: false

run:
  gpu: 0
  device: cuda
  seed: 42
  num_workers: 4
  episodic: false
  runs: 10
  initial_batch_size: 1
  
  use_wandb: false


